CREATE TABLE [dbo].[LoadLevelling]
(
	[ID] [INT] IDENTITY(1,1)  PRIMARY KEY,
	[PRODUCTION_CATEGORY] CHAR(2) NOT NULL,
	[IND_SEASONAL_STATUS] NVARCHAR(128) NOT NULL,
	[TCH_WEEK] CHAR(6) NOT NULL,
	[PLANNING_LEVEL] CHAR(10) NOT NULL,
	[EVENT] CHAR(10),
	[WEEK] CHAR(6) NOT NULL,
	[a] FLOAT DEFAULT 0 NOT NULL,
	[b] FLOAT NOT NULL DEFAULT 0,
	[c] FLOAT NOT NULL DEFAULT 0,
	[d] FLOAT NOT NULL DEFAULT 0,
	[e] FLOAT NOT NULL DEFAULT 0,
	[f] FLOAT NOT NULL,
	[g] FLOAT NOT NULL DEFAULT 0,
	[h] FLOAT NOT NULL DEFAULT 0,
	[i] VARCHAR(10) NOT NULL,
	[j] CHAR(1) NOT NULL,
	[k] FLOAT NULL DEFAULT 0
)
