CREATE TABLE [dbo].[LoadLevelling]
(
	[Id] [INT] IDENTITY(1,1)  PRIMARY KEY,
	[PRODUCTION_CATEGORY] CHAR(2) NOT NULL,
	[IND_SEASONAL_STATUS] NVARCHAR(128) NOT NULL,
	[TCH_WEEK] CHAR(6) NULL,
	[PLANNING_LEVEL] CHAR(10) NOT NULL,
	[EVENT] CHAR(10),
	[WEEK_PLAN] CHAR(6) NOT NULL,
	[Ahead] SMALLINT NOT NULL,
	[Late] SMALLINT NOT NULL,
	[Priority] SMALLINT NOT NULL,
	[Capacity] FLOAT NOT NULL,
	[Required] FLOAT NOT NULL,
	[1] SMALLINT,
	[2] SMALLINT,
	[3] SMALLINT,
	[4] SMALLINT,
	[PLAN_BU] CHAR(10) NOT NULL,
	[FLAG_HR] CHAR(1) NOT NULL,
	[ALLOCATED] FLOAT,
	[NOT_ALLOCATED] FLOAT
)
